MeghDev/force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MeghDev/force-app/main/default/objects/Financial_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

DevOrg/meghDevOrg/force-app/main/default/objects/Insurance_Policy__c/Insurance_Policy__c.object-meta.xml
<CustomObject>
    <label>Insurance Policy</label>
    <nameField>
        <label>Insurance Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOrg/meghDevOrg/force-app/main/default/objects/Insurance_Policy__c/fields/Master_Account__c.field-meta.xml
<CustomField>
    <fullName>Master_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance Policy</relationshipLabel>
    <relationshipName>Insurance_Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

MeghDev/force-app/main/default/classes/relatedRecordsListTest.cls
@IsTest

public with sharing class relatedRecordsListTest{

	@isTest
    public static void getrelatedRecordsTest() {
     
         system.debug('test class called');
         Id accId = '0016F00003xcvX4QAI';
     
         Insurance_Policy__c policy1 = new Insurance_Policy__c(Name='Policy Test1',Master_Account__c='0016F00003xcvX4QAI');
         insert policy1;
         
         Financial_Account__c financiaAcc = new Financial_Account__c(Name='Fianacial Policy 1',Account__c='0016F00003xcvX4QAI');
         insert financiaAcc;
         
         Test.startTest();
             List<SObject> combinedList = relatedRecordsList.getrelatedRecords(accId);
         Test.stopTest();
     }

}