MeghDev/force-app/main/default/objects/Financial_Account__c/Financial_Account__c.object-meta.xml
<CustomObject>
    <label>Financial Account</label>
    <nameField>
        <label>Financial Accounts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MeghDev/force-app/main/default/objects/Financial_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financial Accounts</relationshipLabel>
    <relationshipName>Financial_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

DevOrg/meghDevOrg/force-app/main/default/objects/Insurance_Policy__c/Insurance_Policy__c.object-meta.xml
<CustomObject>
    <label>Insurance Policy</label>
    <nameField>
        <label>Insurance Policy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Policies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOrg/meghDevOrg/force-app/main/default/objects/Insurance_Policy__c/fields/Master_Account__c.field-meta.xml
<CustomField>
    <fullName>Master_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Insurance Policy</relationshipLabel>
    <relationshipName>Insurance_Policies</relationshipName>
    <type>Lookup</type>
</CustomField>

DevOrg/meghDevOrg/force-app/main/default/classes/relatedRecordsList.cls
public with sharing class relatedRecordsList{

    @AuraEnabled
    public static List<SObject> getrelatedRecords(Id recordId) {
    
        List<SObject> getResults = new List<SObject>();
        
        List<Insurance_Policy__c> insuarncePolicy = [Select Id, Name,Master_Account__c from Insurance_Policy__c where Master_Account__c='0016F00003xcvX4QAI'];
        getResults.addAll(insuarncePolicy);
        system.debug('List of insuarncePolicy>>'+insuarncePolicy);
        
        List<Financial_Account__c> financialAcc =  [Select Id,Name,Account__c from Financial_Account__c where Account__c='0016F00003xcvX4QAI'];
        getResults.addAll(financialAcc);
        system.debug('List of financialAcc>>'+financialAcc);
        
        system.debug('final List>>getResults>>>'+getResults);
        
        return getResults;
    
    }

}